### PR TITLE
import 'module-name' support

### PR DESCRIPTION
**Pull request by elderfo**
Added support for `import 'module-name'` along with associated tests (issue #25)

### CODE REVIEW

**Comment by ChristianKohler** [comment]
Thank you @elderfo for your contribution. Looks very good. I will review the pull request in detail in the next few days.

**Comment by elderfo** [comment]
@ChristianKohler thank you!

**Comment by brian221** [comment]
Came for this and found it!  Can't wait 👍

**Comment by ChristianKohler** [comment]
Thank you @elderfo. Great addition to the plugin. I'll publish a new version with your pr today.

**Pull request merged**
